- libs/utils/reputationAPI.ts
Make it easier to change API route and also obfuscate from user
- put route in env var
> Put route in env var

- archetypes/Stake/StakeGeneric/index.tsx
- components/General/UnsupportedNetworkPopup/index.tsx
- context/FarmContext/index.tsx
Staking pools do not load on refresh
- use provider instead of signer 
- add undefined provider safety
> Use provider instead

- context/FarmContext/index.tsx
Fix stake error and unstake error
> Fix stake error

- pages/index.tsx
- pages/stakebpt/index.tsx
- pages/stakepooltoken/index.tsx
Only show onboarding when the user clicks the question mark in the top-right corner.
> Remove onboarding auto trigger

- context/SwapContext.tsx
- libs/constants/poolLists.ts
Quote asset for 'Markets' should be USD not USDC
> Update quote asset

- archetypes/BalancerBuySell/index.tsx
- archetypes/Exchange/Buy/index.tsx
- archetypes/Exchange/Summary/index.tsx
- context/SwapContext.tsx
Style link to balancer page
- add market, leverage and side select to link to balancer page
> Style direct to balancer

- archetypes/Browse/PoolsTable/index.tsx
- archetypes/Browse/index.tsx
Need to fix the issue where in Browse tab if users search for non matching terms it shows the loading icon as if it is still searching.
> Fix loading showing for no matching search result

- archetypes/Pools/PoolsTable/index.tsx
Thought we could just push it now as they're small changes and the next release might not be for weeks
Push changes re the USD >> USDC on the column headers on the pools page
> Update metrics on pools page

- archetypes/Portfolio/History/index.tsx
- archetypes/Portfolio/Queued/index.tsx
- libs/utils/converters.ts
- libs/utils/rpcMethods.ts
- libs/utils/tradeHistoryAPI.ts
Trade history needed some updates
- Use pagination parameters when fetching and displaying trade history
- Add token actions (view on explorer and add to wallet) to trade history rows
- Minor styling consistency updates
> Trade History Updates

- context/Web3Context/Web3Context.Config.ts
Toke farm rewards have ended but UI doesn't displa that
Flag toke farm rewards as ended in config
> end toke farm rewards

- archetypes/BalancerBuySell/index.tsx
Sprint - Jan 10 - Jan 14
General Bugs - Task 1 of #393
> Add connect wallet button to tokens page

- context/Web3Context/Web3Context.Config.ts
LINK LM rewards have ended but UI doesn't know
flag LINK farms as ended
> end link farms

- archetypes/Pools/index.tsx
- archetypes/Pools/state.ts
Update market filter to filter for AAVE not FRAX
> Update market filter

- archetypes/Portfolio/History/index.tsx
- archetypes/Portfolio/Overview/index.tsx
- archetypes/Portfolio/Queued/index.tsx
- libs/hooks/useQueuedCommits/index.tsx
- libs/types/General.ts
- libs/utils/tradeHistoryAPI.ts
- public/img/logos/currencies/frax.svg
Use quote token symbol in the queued commit table
> Use quote token symbol on queued commits

- archetypes/Stake/FarmsTable/index.tsx
Large apys make the app look buggy. Limit to 1bil APY
> Add check for very large apy's

- styles/index.css
I was having a lot of issues matching the design in figma it and turned out to be a font issue.
I can create a PR to merge with develop if this is not a good option.
This change shifts a lot of things around... I didn't see any negative impact initially.
> Update font name

- components/Nav/Navbar/VersionToggle.tsx
- components/Nav/Navbar/index.tsx
> Add v1 toggle to v2 nav bar

- context/Web3Context/Web3Context.Config.ts
- libs/hooks/useEscrowHoldings/index.ts
- libs/hooks/useSubgraphAggregateBalances/index.tsx
Get aggregate balances from subgraph and append to escrow rows
> Fetch subgraph aggregates and append to escrow rows

- archetypes/Exchange/Gas/index.tsx
- archetypes/Exchange/Summary/index.tsx
- archetypes/Exchange/index.tsx
- archetypes/Portfolio/History/index.tsx
- archetypes/Portfolio/Queued/index.tsx
- archetypes/Portfolio/index.tsx
- components/General/Button/ExchangeButton.tsx
- components/General/Checkbox/index.tsx
- components/General/TWButtonGroup/index.tsx
- components/General/TWModal/index.tsx
- components/Nav/Navbar/CommitDropdown.tsx
- components/PendingCommits/index.tsx
- context/PoolContext/index.tsx
- context/ThemeContext/themes.ts
- context/UsersCommitContext/commitDispatch.ts
- context/UsersCommitContext/index.tsx
- libs/constants/index.tsx
- libs/hooks/useCommitsBreakdown/index.tsx
- libs/hooks/useHistoricCommits/index.tsx
- libs/hooks/useQueuedCommits/index.tsx
- libs/types/General.ts
- libs/utils/converters.ts
- libs/utils/reputationAPI.ts
- libs/utils/tradeHistoryAPI.ts
- yarn.lock
Add Flip UI to commit modal
Will add flip and summary logic with #432 and #434
> Flip commit type

- components/Nav/Navbar/AccountBalance.tsx
User balance display has been bugging me
> Fix balance display

- archetypes/Exchange/Summary/index.tsx
- archetypes/Exchange/index.tsx
- components/General/Button/ExchangeButton.tsx
- context/PoolContext/index.tsx
Mint Modal Expected Exposure Breakdown #432 
- Total Costs
- Commit Amount
- Gas Fee
- Expected Tokens Minted
- Expected Amount
- Expected Price
- Expected Equivalent Exposure
- Commit Amount 
- Pool Power Leverage
> V2: Add mint summary logic

- archetypes/ArbitrumBridge/MultiBridge.tsx
- archetypes/Exchange/Inputs/index.tsx
- components/General/Max/index.tsx
- context/ThemeContext/themes.ts
- libs/constants/pool.ts
Style the max button
- capitalise letters
- change colours
- add isDark boolean to themes
> Style Max button

- archetypes/Exchange/Summary/index.tsx
- archetypes/Exchange/index.tsx
- libs/constants/pool.ts
> Estimate burn gas fee

- package.json
- pages/index.tsx
- public/scripts/mat.js
- yarn.lock
> chore: Update vyps-kit

- package.json
- pages/index.tsx
- yarn.lock
> chore: Update vyps

- archetypes/Exchange/Summary/index.tsx
- archetypes/Exchange/index.tsx
> Flip summary

- archetypes/Pools/PoolDetailsModal/index.tsx
- archetypes/Pools/PoolsTable/index.tsx
- components/General/Checkbox/index.tsx
- components/General/Input/index.tsx
- components/OnboardModal/ProgressIndicator.tsx
- components/OnboardModal/Stake.tsx
- components/OnboardModal/Trade.tsx
- components/OnboardModal/styles.tsx
Handle theme state directly in css instead of importing theme context
> Remove isDark prop drilling

- archetypes/Exchange/Inputs/AmountInput.tsx
- archetypes/Exchange/Inputs/index.tsx
- archetypes/Exchange/Inputs/styles.tsx
- archetypes/Exchange/Inputs/types.ts
- archetypes/Exchange/TokenSelect/TokenSelect.tsx
- archetypes/Exchange/TokenSelect/styles.tsx
- archetypes/Exchange/index.tsx
- archetypes/Pools/PoolDetailsModal/index.tsx
- archetypes/Pools/PoolsTable/index.tsx
- archetypes/Portfolio/Overview/EscrowTable/EscrowTable.tsx
- archetypes/Portfolio/Overview/TokenTable/index.tsx
- components/General/Button/ExchangeButton.tsx
- components/PendingCommits/index.tsx
- components/Tooltips/index.tsx
- context/PoolContext/helpers.ts
- context/PoolContext/index.tsx
- context/SwapContext.tsx
- libs/constants/index.tsx
Update commit input designs to allow for users to select if they want to use tokens from the aggregate balances or directly from their wallet.
- full width token select
- add wallet select button toggle
- pass wallet select param into commit
> Add wallet type select

- archetypes/Stake/StakeGeneric/index.tsx
- components/Nav/Navbar/AccountBalance.tsx
- context/ArbitrumBridgeContext/index.tsx
- context/PoolContext/index.tsx
- package.json
- store/ThemeSlice/index.tsx
- store/TransactionSlice/index.tsx
- store/main.ts
- store/types.ts
- yarn.lock
Add lenses and seperate slices into seperate sections of the global store
> Add lens to create subset get and sets

- context/PoolContext/index.tsx
- context/UsersCommitContext/commitDispatch.ts
- libs/hooks/useQueuedCommits/index.tsx
- libs/types/General.ts
- libs/utils/tracerAPI.ts
Use subgraph query instead of the API temporarily
> Use subgraph instead of API

- archetypes/Pools/AddAltPoolModal/index.tsx
- archetypes/Pools/AddAltPoolModal/messages.tsx
- archetypes/Pools/AddAltPoolModal/styles.tsx
- archetypes/Pools/FilterSelects/Bar.tsx
- archetypes/Pools/index.tsx
- archetypes/Pools/state.ts
- components/General/SearchInput/index.tsx
- components/General/TWModal/index.tsx
- libs/utils/address.tsx
- store/PoolsSlice/index.tsx
- store/PoolsSlice/types.ts
- store/main.ts
- store/types.ts
https://www.figma.com/file/gA9jQ5B6ZwWjGKBhGUFbKo/2.0-Pools?node-id=573%3A300635
> Add alt pool modal

- components/General/Notification/Commit.tsx
- components/General/Notification/Icon.tsx
- components/General/Notification/Notification.tsx
- components/General/Notification/ToastContainerWithStyles.tsx
- store/TransactionSlice/transactions.tsx
https://www.figma.com/file/gA9jQ5B6ZwWjGKBhGUFbKo/2.0-Pools?node-id=117%3A217937
> Toast design updates

- hooks/usePoolTokens/index.tsx
Fix duplicate in token select dropdown
> Fix token balances bug

- archetypes/Portfolio/Overview/HoldingsTable/Actions.tsx
- archetypes/Portfolio/Overview/state.ts
Disable denote in filter
https://tracerdao.notion.site/Denote-in-base-doesn-t-work-would-make-sense-to-turn-this-into-a-coming-soon-same-as-the-price--7d1b78c67f4445b1ad0f58ebe2ba58e9
> Disable denote in filter

- archetypes/Pools/index.tsx
- archetypes/Pools/state.ts
Update leverage filter to include 3, 5 and 7
Ideally this would not be hardcoded in at all and would be created by mapping over all the pools
> Update leverage filters

- archetypes/Exchange/Summary/FlipSummary.tsx
- archetypes/Exchange/Summary/MintSummary.tsx
- archetypes/Exchange/Summary/Sections.tsx
- archetypes/Exchange/Summary/index.tsx
- archetypes/Exchange/Summary/types.ts
Update short exposure color
https://tracerdao.notion.site/Change-short-exposure-colour-in-mint-summary-3ae23d58383d4eee8d265adebec877df
> Update short exposure color

- pages/trading-comp/index.tsx
> Trading comp background fix

- archetypes/Exchange/Summary/MintSummary.tsx
- archetypes/Exchange/Summary/Sections.tsx
Sentence case summary text
https://www.notion.so/tracerdao/0dae7793a7e240eaa9c2fa66a6c6d348?v=c6d9f70180f54c2da4ef257a97ad88b0&p=036f8f2213ec4c8c8de4b573a4114fa6
> Sentence case summary

- archetypes/Pools/PoolsTable/index.tsx
> Remove index price tip

- archetypes/Exchange/Summary/Sections.tsx
- archetypes/Portfolio/Overview/SkewCard/index.tsx
- archetypes/Portfolio/Overview/index.tsx
- archetypes/Portfolio/Overview/state.ts
- hooks/useBrowsePools/index.tsx
- hooks/usePoolWatcher/index.tsx
- hooks/useUserTokenOverview/index.tsx
Remove unrealised PNL and Acquisition costs from the portfolio page
> Remove unrealised pnl and acquisition costs

- hooks/useUpkeeps/index.tsx
- utils/tracerAPI/api.ts
- utils/tracerAPI/subgraph.ts
fetch last upkeeps from the graph to show last rebalance stats on pool page
> fetch upkeeps from the graph instead of api

- archetypes/Pools/state.ts
Update filter dropdowns to only show relative markets and settlement tokens https://www.notion.so/tracerdao/0dae7793a7e240eaa9c2fa66a6c6d348?v=c6d9f70180f54c2da4ef257a97ad88b0&p=f758c3dfb3d54b2cb48c4c7fdbc82916
> Update market and collateral filter

- components/TradingComp/ArticleBox.tsx
- pages/trading-comp/index.tsx
- Add second tile for video tutorial on minting and burning
> Update trading comp article link

- package.json
- yarn.lock
Update pools-js version to include new calc changes
> Udpate pools js

- archetypes/Portfolio/Queued/index.tsx
Fix pending mint commit display
> Fix pendig commits

- components/TradingComp/UserTable.tsx
Add z index to trading comp table headers so they all remain on scroll
> Add z-index to headers

- archetypes/Exchange/Inputs/index.tsx
- components/Tooltips/TooltipSelector/index.tsx
- components/Tooltips/index.tsx
> Disable escrow button mint long

- components/Nav/Navbar/VersionToggle.tsx
- components/Nav/Navbar/index.tsx
Fix nav breakpoints and add v2 toggle to master
> Fix nav breakpoints

- components/TradingComp/ArticleBox.tsx
- components/TradingComp/CountdownBanner.tsx
- components/TradingComp/Leaderboard.tsx
- pages/trading-comp/index.tsx
- Prevent overflow
- Move bug bounty onto new line when width too small
- Make Article and Tutorial tiles full width on mobile
> Fix bug bounty amount going off screen

- archetypes/Portfolio/Overview/index.tsx
Use token valuation instead of full notional value
> Change token valuation

- archetypes/Portfolio/Queued/NoQueuedCommits.index.tsx
- archetypes/Portfolio/Queued/index.tsx
- hooks/usePoolWatcher/index.tsx
Fix flip commit display
- remove duplicate `no commits` component
> Fix display of flip commits and refactor code a little

- archetypes/Exchange/Inputs/index.tsx
- archetypes/Portfolio/History/index.tsx
- archetypes/Portfolio/Overview/index.tsx
> Fix mint commit history

- components/TokenActions/index.tsx
- package.json
- yarn.lock
> Update token actions popover

- archetypes/Pools/index.tsx
- archetypes/Portfolio/index.tsx
> Keep modal from rendering if not in use

- components/Nav/Navbar/MobileMenu/Hamburger.tsx
-Adjust height so all bars look the same
-Set cursor to pointer
> Adjust height and set cursor to pointer

- archetypes/Portfolio/Overview/content.ts
- archetypes/Portfolio/Overview/index.tsx
Update card content in portfolio page
https://www.notion.so/tracerdao/Portfolio-Page-Mar-Comms-Tiles-39f4cd844ce44338a84b0757862f924d
> Update card content in portfolio page

- archetypes/Portfolio/Overview/ConnectWalletBanner/styles.tsx
Remove background color from connect banner
https://www.notion.so/tracerdao/PPv2beta-feedback-f0f104b8d22d416fb098629bca69b727?p=94d029739724415c970c01c90893b80c
> Remove background color

- components/Footer/index.tsx
- components/Nav/Navbar/HeaderSiteSwitcher.tsx
Update github link to link directly to contracts
https://www.notion.so/tracerdao/PPv2beta-feedback-f0f104b8d22d416fb098629bca69b727?p=9dc6519f9a674020b30e2b25505e1cbc
> Update github link

- components/Nav/Navbar/AccountDropdown/AccountDropdown.tsx
Copy checksummed address instead of lowercase address
> Copy checksummed address

- components/Nav/Navbar/MobileMenu/Hamburger.tsx
- components/Nav/Navbar/MobileMenu/index.tsx
Close the mobile menu when user clicks outside of mobile menu or clicks escape.
https://www.notion.so/tracerdao/PPv2beta-feedback-f0f104b8d22d416fb098629bca69b727?p=01ae991a729b4a99894f86717e62ce09
> Close menu with outside click

- components/Footer/index.tsx
Update `Security Audit` to `Security Audits` and change link
https://www.notion.so/tracerdao/PPv2beta-feedback-f0f104b8d22d416fb098629bca69b727?p=bed5dccaabcb4a8fad9d66e1e8f23d32
> Udpate audits link

- .eslintrc.js
- components/General/Hide/index.tsx
- components/General/Show/index.tsx
- components/Nav/Navbar/AccountDropdown/styles.tsx
- components/Nav/Navbar/MobileMenu/index.tsx
- components/Nav/Navbar/index.tsx
> Go to mobile breakpoint later

- archetypes/Pools/index.tsx
Decapitlise pools copy content on the Pools page
> Decapitalise pools on Pools page

- archetypes/Portfolio/TradeOverviewBanner/styles.tsx
Restyle portfolio banner dropdown styles to match designs
https://www.figma.com/file/gA9jQ5B6ZwWjGKBhGUFbKo/2.0-3.0-Pools?node-id=269%3A259065
https://tracerfinance.atlassian.net/browse/PML-115
> Fix banner dropdown styles

- archetypes/Portfolio/ClaimedTokensTable/ClaimedTokensTable.tsx
- archetypes/Portfolio/UnclaimedTokens/UnclaimedTokensTable.tsx
Add no table entries to claimed and unclaimed tokens
> Add no table entries to claimed and unclaimed tokens

- archetypes/Portfolio/HelpCard/index.tsx
- archetypes/Portfolio/HelpCard/styles.tsx
- archetypes/Portfolio/TradeOverviewBanner/index.tsx
- archetypes/Portfolio/index.tsx
- Remove skew farm title when wallet connected
- remove rounded top borders for skew farm card 
- use the same TradeBanner component for both connected and disconnected states
- Remove portfolio delta if its 0
https://tracerfinance.atlassian.net/browse/PML-114
> Pml 114 remove skew farm tile

- constants/pools.ts
- styles/index.css
- utils/poolNames.ts
- utils/rpcMethods.ts
- Add token actions z-index
- shorten token symbols to make metamask happy
> Set popover z-index

- archetypes/Portfolio/OverviewTable/index.tsx
- archetypes/Portfolio/OverviewTable/styles.tsx
Allow opening of portfolio tables on row click
https://tracerfinance.atlassian.net/browse/PML-122
> Open portfolio table on row click

- archetypes/Exchange/FeeNote/index.tsx
- archetypes/Pools/index.tsx
- components/Footer/index.tsx
- components/General/UnsupportedNetworkPopup/index.tsx
- components/Nav/Navbar/HeaderSiteSwitcher.tsx
- components/Nav/Navbar/MobileMenu/index.tsx
- components/Nav/Navbar/index.tsx
- components/Tooltips/index.tsx
- utils/poolNames.ts
Update documentation links throughout
https://tracerfinance.atlassian.net/browse/PML-123
> Update doc links

- archetypes/Portfolio/ClaimedTokensTable/ClaimedTokenRow.tsx
- archetypes/Portfolio/ClaimedTokensTable/ClaimedTokensTable.tsx
- archetypes/Portfolio/ClaimedTokensTable/index.tsx
- archetypes/Portfolio/UnclaimedTokens/UnclaimedTokensRows.tsx
- archetypes/Portfolio/UnclaimedTokens/UnclaimedTokensTable.tsx
- archetypes/Portfolio/UnclaimedTokens/index.tsx
- archetypes/Portfolio/index.tsx
- archetypes/Portfolio/state.ts
- archetypes/Stake/StakeGeneric/index.tsx
Set balanceType when clicking commit from unclaimed tokes
https://tracerfinance.atlassian.net/browse/PML-135
> Set balanceType on clickCommit

- archetypes/Portfolio/QueuedCommits/QueuedCommitRow.tsx
> Set out token symbol

- hooks/usePoolInstanceActions/index.ts
- hooks/useUserClaimedTokens/index.tsx
- store/PoolInstancesSlice/index.tsx
Update pool token balances after commit
> Update pool token balanaces after commit

- public/scripts/matomo.js
- store/PoolInstancesSlice/index.tsx
> Update matamo script

- constants/staking.ts
> add new pool token farm addresses

- archetypes/Stake/FarmsTable/index.tsx
- archetypes/Stake/StakeGeneric/index.tsx
- archetypes/Stake/StakeModal/index.tsx
- archetypes/Stake/state.ts
- constants/staking.ts
- store/TransactionSlice/transactions.tsx
https://tracerfinance.atlassian.net/jira/software/projects/PML/boards/24?selectedIssue=PML-140
- add max decimals to stake modal 
- autoclose toast on stake transaction failures
> staking modal fixes

- archetypes/Pools/index.tsx
Update pools text as per https://discord.com/channels/808906099172442122/975630612360724561/976452524540297326
> Update pools text

- components/Footer/index.tsx
- components/Nav/Navbar/MobileMenu/index.tsx
- components/Nav/Navbar/index.tsx
https://tracerfinance.atlassian.net/jira/software/projects/PML/boards/24?selectedIssue=PML-132
- update various docs links
> update docs links

- hooks/usePortfolioOverview/index.tsx
> Fix amounts used in calcs

- .github/workflows/main.yml
- .gitignore
- archetypes/Pools/PoolsTable/index.tsx
- components/General/Dropdown/index.tsx
- hooks/usePortfolioOverview/index.tsx
- hooks/usePortfolioOverview/usePortfolioOverview.test.js
- hooks/usePortfolioOverview/usePortfolioOverview.test.ts
- jest.config.js
- package.json
- yarn.lock
Add portfolio banner hook test
- test the hook handles mints/burns
- test disconnected account
- test wallet and escrow balances
- add test action
> Add basic test

- utils/farms.ts
Use original fetch token price for farms
> Use original token fetch price

- archetypes/Pools/index.tsx
- archetypes/Pools/styles.tsx
Fix disabled button tooltip hover. The issue is disabled components dont fire events and this tooltip binds to the child element. The solution has a couple of things going on.
- wrap the button in a div so the tooltip can bind to the div
- z-index the button and add a dummy button component which has the cursor disabled
- disable all pointer events on the button
> Fix deploy pool coming soon tip

- context/Web3Context/Web3Context.Config.ts
flag all remaining staking farms as ended
> end staking rewards for all v1 farms
