tracer-protocol/pools-client

context/PoolContext/index.tsx, libs/hooks/useBrowsePools/index.tsx
Moving between networks was causing an application crash when it picked up on old event listeners.
- check that the subscription providers network matches the currently selected providers network. If they dont match the remove all the event listeners and dont update the poolsState
=> Remove listeners if an old subscription picks up an event

libs/utils/rpcMethods.ts, package.json, yarn.lock
Balancer spot pricing was slightly off because swap fees were not included in calcs
- update `tracer-pools-utils` to latest version
- query swapFee from balancer graph and pass into spot price calc function
=> [balancer spot price] add swapFee to calculations

context/PoolContext/poolDispatch.ts
Since pools are getting reset on network change there are some returning async requests which are trying to set info for old pools causing it to crash.
To reproduce
- connect to arbitrum
- clear cache
- connect
Since it initially loads the mainnet pools via the websocket, then connecting changes network to the testnet, the returning calls to balances and and commit info cause it to crash
- add checks if state.pools[pool] exists. If it doesnt then just ignore it
=> Prevent setting when pools have been cleared

components/General/UnsupportedNetworkPopup/index.tsx, context/PoolContext/index.tsx
- pools list undefined for unsupported networks
- ensure unsupported network pops up
- fail safe on pools init
=> Add safety for unsupported networks, fix poopup

archetypes/Exchange/Buy/index.tsx, components/ArbitrumBridge/MultiBridge.tsx, context/ArbitrumBridgeContext/index.tsx
Show 8 days as the time taken to withdraw ETH/USDC from Arbitrum just as Arbitrum bridge displays.
=> Update time taken to withdraw from Arbitrum

archetypes/Stake/FarmsTable/index.tsx, archetypes/Stake/StakeGeneric/index.tsx, components/Tooltips/index.tsx, context/FarmContext/index.tsx, context/Web3Context/Web3Context.Config.ts, libs/types/Staking.ts
the staking rewards have ended but the UI implies they are still active
add `rewardsEnded` attribute to pools farm config and use it on the EUR/USD pools
=> add `rewardsEnded` staking farm config option, apply to EUR pools

archetypes/Stake/FarmsTable/index.tsx, archetypes/Stake/StakeBPT/index.tsx, archetypes/Stake/StakeGeneric/index.tsx, archetypes/Stake/StakePool/index.tsx, context/FarmContext/index.tsx, libs/types/Staking.ts
We plan on launching a staking farm where rewards are paid in FXS. Currently, the UI only supports LM rewards paid in TCR. 
Generalize the storage of reward token pricing so we can add additional reward token prices for use in APY/APR calculations
=> generalise staking reward asset pricing to prep for FXS staking rewards

archetypes/BalancerBuySell/index.tsx, context/ThemeContext/index.tsx, context/ThemeContext/themes.ts
Am proposing we slowly start using styled components. Every time I leave the code base and come back to tailwind after a while I just dislike it. We are using styled-components in pools-ui and its so much more usable imo. This shouldnt break any existing functionality, but will provide the theme contexts to create new components if you want to. Over time we can slowly start to convert old components, and they will also be slowly pushed into pools-ui component library as well.
Components are created and styled as 
```
const Wrap = styled.div`
background-color: ${({ theme }) => theme.colors.background};
`;
```
This way we can go back to writing css. The main benefit I see of styled-components is 
- easier to follow designs. Tailwind allows you to have full custom css but it takes some …
=> Add styled components themes

archetypes/Stake/StakeBPT/index.tsx, archetypes/Stake/StakePool/index.tsx, context/FarmContext/index.tsx, context/Web3Context/Web3Context.Config.ts
When we release staking farms paid in FXS, we need the USD price of FXS to calculate reward rates
- Refactor fetching of reward token pricing to support arbitrary tokens
- Add FXS as a known staking reward token, this causes the farm context to fetch its USDC price during initialization
=> add FXS USD pricing for use in LM reward calcs

archetypes/BalancerBuySell/index.tsx, context/UsersCommitContext/commitDispatch.ts, libs/utils/reputationAPI.ts
Ticket for #437 
Pending commits were not showing after after toaster minimised. This is because the API request had a slight error in it.
- use txn hash to identify commits instead of ID. Reputation does not return the commit ID
- fix request route
=> Fix pending commits

context/Web3Context/Web3Context.Config.ts
AAVE/USD staking farms are finishing soon
mark the farm as ended so that the UI tells users the rewards are over
=> mark aave/usd staking farms as ended

archetypes/Pools/index.tsx
Add href to learn more link
https://tracerdao.notion.site/Learn-more-is-not-live-in-page-description-need-to-point-this-to-docs-pools-docs-tracer-finance--521b13efc5d245d18ae2cf96d32b9068
=> Pools add learn more link

hooks/useAllPoolLists/index.ts, hooks/usePoolWatcher/index.tsx, hooks/useUpdatePoolInstances/index.ts, hooks/useUpkeeps/index.tsx, store/PoolsSlice/index.tsx, store/Web3Slice/index.ts
Handle proper selection of poolLsits. This fixes the bug of pools not reloading when network changes
- create usePoolLists hook which fetches the pools list based on the network, uses a memoized selector to avoid multiple selections
- only update ref when poolsList changes
=> Properly handle selection of poolLists

components/TokenActions/index.tsx, hooks/usePoolInstanceActions/index.ts, hooks/usePoolWatcher/index.tsx, store/PendingCommitSlice/index.tsx
Add commit in commit callback, this assures the user doesnt have to wait to see their pending commit, commits are based on txnHash as their key so should not cause double ups.
=> Add commit straight after txn

components/Nav/Navbar/MobileMenu/index.tsx, components/Nav/Navbar/index.tsx
-Remove nested "a" tag to remove warning
-Fix mobile nav links
old
new
=> Fix mobile nav links

archetypes/Exchange/Inputs/index.tsx, components/Tooltips/TooltipSelector/index.tsx, components/Tooltips/index.tsx
We temporarily disabled long minting from escrow for the trading comp due to a contract bug. Contracts have been redeployed with a fix so this no longer applies
re-enables long mint from escrow (essentially reverts changes from https://github.com/tracer-protocol/pools-client/pull/580)
=> re-enable long mint from escrow balance

archetypes/Portfolio/OverviewTable/styles.tsx
https://tracerfinance.atlassian.net/browse/PML-111
Remove fixed search height on the portfolio page. Effects smaller height screens when base font size gets reduced.
To test reduce height of screen to 750px
=> Remove fixed search height

archetypes/Exchange/Inputs/AmountInput.tsx, archetypes/Exchange/Inputs/index.tsx, archetypes/Exchange/Summary/MintSummary.tsx, archetypes/Exchange/Summary/Sections.tsx, archetypes/Exchange/Summary/index.tsx, archetypes/Exchange/Summary/types.ts, archetypes/Exchange/TokenSelect/TokenSelect.tsx
Set token price decimals to 3 as per https://tracerfinance.atlassian.net/browse/PML-71
Sorry forgot to name branch after ticket.
- set token price to 3 decimal places
- use settlementTokenSymbol instead of USD
=> Set token price to three decimal places

archetypes/Portfolio/HistoricCommits/index.tsx, archetypes/Portfolio/UnclaimedTokens/UnclaimedTokensRows.tsx, hooks/useHistoricCommits/index.tsx, hooks/usePagination/index.tsx
- Convert historic commits table to 6 page entries.
- Fix notional value display of unclaimed tokens
https://tracerfinance.atlassian.net/browse/PML-116
Note: doesnt actually use the usePagination hook any more but thought Id update anyway
=> Convert page entries to 6

utils/tracerAPI/api.ts
fee from trade history api is always in WAD format so always format with 18 decimal places instead of `settlementToken` decimals
=> always format trade history fees as 18 decimal places

archetypes/Stake/StakeGeneric/index.tsx, components/BaseFilters/index.tsx
Reduce search bar sizes to match designs, pretty hard to tell in these screenshots but just reduced 2.5px in height, lol
https://www.figma.com/file/gA9jQ5B6ZwWjGKBhGUFbKo/2.0-3.0-Pools?node-id=1911%3A164247
=> Reduce search bar sizes

archetypes/Portfolio/Market.tsx, utils/poolNames.ts
Set token names to general Short/Long tokens. Skips if the token symbol is not recognized as a pool token symbol which has the form {LEVERAGE}{L/S}-{POOL_NAME}
https://tracerfinance.atlassian.net/browse/PML-126
=> Convert to general token names

hooks/usePortfolioOverview/index.tsx
I noticed that the portfolio page did not account for the money spent on pending mints and said I was up the full amount that I spent.
before:
after:
=> include the pending mint spend in portfolio delta

context/FarmContext/index.tsx, hooks/useFarmBalances/index.tsx, hooks/usePortfolioOverview/index.tsx, hooks/usePortfolioOverview/usePortfolioOverview.test.ts, pages/portfolio.tsx, types/staking/index.ts, utils/farms.ts
Handle staked pool tokens on portfolio page. Uses pool token amounts such that the token price matches the token price used on the portfolio page. Creates a mapping from token address to staked balances. Uses this mapping in usePortfolioOverview to add staked token amounts to the users portfolio. Acts as if the tokens were not staked and are still in wallet balance. This is because totalSettlement spend does not change after staking but wallet balances do, so adding the staked amount replaces the losses in wallet balance
=> Handle staked pool tokens

archetypes/Portfolio/ClaimedTokensTable/ClaimedTokenRow.tsx, archetypes/Portfolio/ClaimedTokensTable/ClaimedTokensTable.tsx, archetypes/Portfolio/ClaimedTokensTable/index.tsx, archetypes/Portfolio/TradeOverviewBanner/index.tsx, archetypes/Portfolio/UnclaimedTokens/UnclaimedTokensRows.tsx, archetypes/Portfolio/UnclaimedTokens/UnclaimedTokensTable.tsx, archetypes/Portfolio/UnclaimedTokens/index.tsx, archetypes/Portfolio/index.tsx, archetypes/Portfolio/state.ts, archetypes/Stake/StakeGeneric/index.tsx, constants/pools.ts, hooks/usePortfolioOverview/index.tsx, hooks/useUserClaimedTokens/index.tsx, hooks/useUserUnclaimedTokens/index.ts, types/claimedTokens.ts, types/portfolio.ts, types/unclaimedTokens.ts
Add stake button to claimed tokens table
- /stake page handles query string params `stake` and `unstake` the values of these params should be a pool token address. The handler will search for the token address in the farms object and will open the relevant modal if it can find it
- preferences stake > unstake, could handle this in a number of ways but would only be the case if someone is intentionally fucking with it and tries to set both
- can handle multiple query string params values but will only ever take first one, again this is just to not break it if someone is fucking with it
- if it cant find the token in the farms then it wont open the modal 
- re structure some types and move them into /types
=> Dev 263 add stake button

constants/pools.ts
pre-emptively guarding against potential rogue pools from showing in the UI. Will fetch pool list from 
https://api.tracer.finance/poolsv2/poolList?network=42161&list=verified
=> add verified query parameter to pool list request

constants/balancer.ts
- add known balancer pool addresses for v2.1 markets (BTC, ETH, WTI)
=> add balancer pool addresses for v2.1 markets

archetypes/Pools/PoolsTable/index.tsx
use `nextSkew` in pools table `next rebalance` view instead of current skew
=> show correct skew in pools table
